### ISSUE TITLE
Contribution view not working

### ISSUE THREAD

**Issue by lpla** [timfraedrich/OutRun#59]
**Describe the bug**

The new contributors page/view is not working, as it shows breen al variables instead.

**To Reproduce**
1. Go to 'Settings'
2. Scroll down to 'Contribution'
3. Get in there

**Expected behavior**

Contributors should be listed with ‘contribution.json’ content

**Screenshots**

![image](https://user-images.githubusercontent.com/1533393/106379070-c7f0c500-63a9-11eb-966a-cc46ffda488e.png)

**Comment by timfraedrich** [comment]
I addressed this in 0585683, I forgot to exchange the keys for actual values and there was a syntax error in the .json file.

But still thanks for pointing it out, I will issue a small update in the next couple of days.

**Comment by jrossstocholm** [comment]
FYI - the contribution page still shows the placeholders mentioned in the original bug reported.
